# yaml-language-server: $schema=config.schema.json

# Organization Info
org:
  name: ohc.network ## required
  description: Open Healthcare Network(OHC) is an open-source platform that helps governments, hospitals, and innovators build connected healthcare systems faster, safer, and at national scale. ## required
  url: https://ohc.network ## required
  logo_url: https://ohc.network/logo.png ## required
  start_date: 2020-03-08 ## optional
  socials: ## optional
    github: https://github.com/ohcnetwork ## optional
    slack: https://slack.ohc.network ## optional
    linkedin: https://linkedin.com/company/ohcnetwork ## optional
    youtube: https://youtube.com/ohcnetwork ## optional
    email: support@ohc.network ## optional

# Site and SEO Metadata
meta:
  title: Leaderboard - Open Healthcare Network ## required
  description: ohc.network Leaderboard tracks the weekly contributions across different contributors working on projects in the organisation. ## required
  image_url: https://ohc.network/logo.png ## required
  site_url: https://contributors.ohc.network ## required
  favicon_url: https://ohc.network/favicon.ico ## required

# Leaderboard related configurations
leaderboard:
  data_source: https://github.com/ohcnetwork/leaderboard-data ## required
  # theme: https://cdn.ohc.network/assets/leaderboard/theme.css ## optional - URL to custom theme CSS file
  roles: ## required (minimum 1 role)
    core:
      name: Core ## required
      description: Core member of OHC ## optional

    intern:
      name: Intern
      description: Intern at OHC

    operations:
      name: Operations
      description: OHC Operations team member

    contributor:
      name: Contributor
      description: Open source contributor

    bot:
      name: Bot
      description: Bot account
      hidden: true ## optional - default: false - hides role by default in leaderboard and excludes from people page

  top_contributors: ## optional - activity definition slugs to show in top contributors sidebar
    - pr_merged
    - pr_opened
    - issue_opened
    - issue_assigned

  social_profiles: ## optional - social profile icon mappings
    github:
      icon: github
    linkedin:
      icon: linkedin
    twitter:
      icon: twitter
    email:
      icon: mail

# Scraper configurations
scrapers: ## optional
  github:
    cron: 0 0 * * *
    source: https://github.com/ohcnetwork/leaderboard-github-scraper ## required
    ## attributes specifically defined by the github scraper (can be any number of unknown attributes)
    org: ohcnetwork
    token: ${{ GITHUB_TOKEN }}

  slack:
    cron: 0 0 * * * ## required
    source: https://github.com/ohcnetwork/leaderboard-slack-scraper ## required
    ## attributes specifically defined by the slack scraper (can be any number of unknown attributes)
    api_key: ${{ SLACK_API_KEY }}
